# <b>Task 12</b>
## Name: Aleeza Fatima
## RollNumber: SU92-BSDSM-S25-009

<h1> Data set link </h1>

<div class ## Step 1:
## Data Reading and Loading

<a> https://www.kaggle.com/datasets/shree0910/ai-job-risk-and-salary-dataset-20152035 </a>

All libraries used in our whole code

In [93]:
import pandas as pd
import numpy as np
import joblib
import pickle   

from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestRegressor # or Classifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

<div class="alert alert-block alert-success">
    <h1>Step 1: Data Ingestion</h1>
</div>

In [94]:
# import pandas as pd
data=pd.read_csv('E:\\aleeza university sem 1\\AI lab\\Project\\Future of Jobs AI Dataset.csv')
data

,job_title,country,experience_level,education_level,year,salary,ai_risk_score,primary_skill,skill_demand_score,job_openings,job_survival_class,salary_bucket,ai_risk_category
0,Data Scientist,USA,Senior,Master,2022,61931.03,0.32,Python,88,39158,2,High,Medium Risk
1,Software Engineer,India,Senior,Bachelor,2032,21330.84,0.52,Java,80,7265,1,High,Medium Risk
2,Data Scientist,Canada,Mid,Bachelor,2015,24211.17,0.25,Python,70,22962,1,High,Low Risk
3,Data Scientist,India,Entry,PhD,2034,11794.86,0.44,Python,95,17023,1,Medium,Medium Risk
4,Data Analyst,Canada,Entry,PhD,2035,17999.26,0.75,SQL,61,3433,0,Medium,High Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12338,Data Scientist,Germany,Entry,Master,2030,27079.49,0.40,Python,89,2395,1,High,Medium Risk
12339,Cybersecurity Analyst,USA,Mid,Bachelor,2028,42474.50,0.28,Security,73,24254,2,High,Low Risk
12340,Software Engineer,India,Senior,Master,2028,19381.43,0.48,Java,77,27356,1,Medium,Medium Risk
12341,AI Researcher,Australia,Entry,PhD,2023,32647.87,0.13,Deep Learning,78,48428,2,High,Low Risk
12342,DevOps Engineer,Australia,Entry,PhD,2023,23197.87,0.28,Docker,92,43405,2,High,Low Risk


<div class="alert alert-block alert-success">
    <h1>Step 2: Exploratory Data Analysis</h1>
</div>

To see starting values of data...
Default 5

In [95]:
data.head()

,job_title,country,experience_level,education_level,year,salary,ai_risk_score,primary_skill,skill_demand_score,job_openings,job_survival_class,salary_bucket,ai_risk_category
0,Data Scientist,USA,Senior,Master,2022,61931.03,0.32,Python,88,39158,2,High,Medium Risk
1,Software Engineer,India,Senior,Bachelor,2032,21330.84,0.52,Java,80,7265,1,High,Medium Risk
2,Data Scientist,Canada,Mid,Bachelor,2015,24211.17,0.25,Python,70,22962,1,High,Low Risk
3,Data Scientist,India,Entry,PhD,2034,11794.86,0.44,Python,95,17023,1,Medium,Medium Risk
4,Data Analyst,Canada,Entry,PhD,2035,17999.26,0.75,SQL,61,3433,0,Medium,High Risk

To see the last values of data...
default value 5

In [96]:
data.tail(9)

,job_title,country,experience_level,education_level,year,salary,ai_risk_score,primary_skill,skill_demand_score,job_openings,job_survival_class,salary_bucket,ai_risk_category
12334,Business Analyst,Germany,Mid,Bachelor,2016,19445.23,0.66,Excel,81,41721,1,Medium,High Risk
12335,Cloud Engineer,India,Senior,Master,2030,26178.07,0.40,AWS,77,11931,1,High,Medium Risk
12336,AI Researcher,Australia,Entry,PhD,2022,32247.79,0.12,Deep Learning,96,26895,2,High,Low Risk
12337,AI Researcher,UK,Entry,Bachelor,2027,37269.00,0.17,Deep Learning,94,49793,2,High,Low Risk
12338,Data Scientist,Germany,Entry,Master,2030,27079.49,0.40,Python,89,2395,1,High,Medium Risk
12339,Cybersecurity Analyst,USA,Mid,Bachelor,2028,42474.50,0.28,Security,73,24254,2,High,Low Risk
12340,Software Engineer,India,Senior,Master,2028,19381.43,0.48,Java,77,27356,1,Medium,Medium Risk
12341,AI Researcher,Australia,Entry,PhD,2023,32647.87,0.13,Deep Learning,78,48428,2,High,Low Risk
12342,DevOps Engineer,Australia,Entry,PhD,2023,23197.87,0.28,Docker,92,43405,2,High,Low Risk

To see the number of rows, columns, data type of each column, non-null values and column name of each column

In [97]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12343 entries, 0 to 12342
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   job_title           12343 non-null  object
 1   country             12343 non-null  object
 2   experience_level    12343 non-null  object
 3   education_level     12343 non-null  object
 4   year                12343 non-null  int64
 5   salary              12343 non-null  float64
 6   ai_risk_score       12343 non-null  float64
 7   primary_skill       12343 non-null  object
 8   skill_demand_score  12343 non-null  int64
 9   job_openings        12343 non-null  int64
 10  job_survival_class  12343 non-null  int64
 11  salary_bucket       12343 non-null  object
 12  ai_risk_category    12343 non-null  object
dtypes: float64(2), int64(4), object(7)
memory usage: 1.2+ MB

To see the number of rows and column...for rows use [0] and for columns use [1]

In [98]:
print(f' Total number of Rows in this dataset are: {data.shape[0]} \n Total number of Columns in this dataset are {data.shape[1]}')

 Total number of Rows in this dataset are: 12343
 Total number of Columns in this dataset are 13

Two ways to see the columns of data

In [99]:
for i in data.columns:
  print(i, end=" ")
# print(data.columns)

job_title country experience_level education_level year salary ai_risk_score primary_skill skill_demand_score job_openings job_survival_class salary_bucket ai_risk_category

To see the number of rows in each column

In [100]:
data.count()

job_title             12343
country               12343
experience_level      12343
education_level       12343
year                  12343
salary                12343
ai_risk_score         12343
primary_skill         12343
skill_demand_score    12343
job_openings          12343
job_survival_class    12343
salary_bucket         12343
ai_risk_category      12343
dtype: int64

Both methods to see the specific column in the dataset

In [101]:
#data.country
data['country']

0              USA
1            India
2           Canada
3            India
4           Canada
           ...
12338      Germany
12339          USA
12340        India
12341    Australia
12342    Australia
Name: country, Length: 12343, dtype: object

To see the unique value in a specific column

In [102]:
data['country'].unique()

array(['USA', 'India', 'Canada', 'UK', 'Germany', 'Australia'],
      dtype=object)

To see the number of unique values in all dataset

In [103]:
data.nunique()

job_title                10
country                   6
experience_level          3
education_level           3
year                     21
salary                12327
ai_risk_score            81
primary_skill             9
skill_demand_score       40
job_openings          10911
job_survival_class        3
salary_bucket             3
ai_risk_category          3
dtype: int64

To check the Count, mean, standard deviation, minimun value, 25% value, half value, 75% value, and maximum value of all the columns separately in the dataset

In [104]:
data.describe()

,year,salary,ai_risk_score,skill_demand_score,job_openings,job_survival_class
count,12343.000000,12343.000000,12343.000000,12343.000000,12343.000000,12343.000000
mean,2025.054525,34553.729166,0.396008,79.453374,25223.652029,1.310054
std,6.058714,18024.702961,0.187665,11.483535,14163.309081,0.658417
min,2015.000000,3875.170000,0.050000,60.000000,1002.000000,0.000000
25%,2020.000000,21331.405000,0.260000,70.000000,12993.000000,1.000000
50%,2025.000000,31573.380000,0.360000,79.000000,24896.000000,1.000000
75%,2030.000000,45307.845000,0.490000,89.000000,37440.500000,2.000000
max,2035.000000,113589.260000,0.850000,99.000000,49998.000000,2.000000

In [105]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12343 entries, 0 to 12342
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   job_title           12343 non-null  object
 1   country             12343 non-null  object
 2   experience_level    12343 non-null  object
 3   education_level     12343 non-null  object
 4   year                12343 non-null  int64
 5   salary              12343 non-null  float64
 6   ai_risk_score       12343 non-null  float64
 7   primary_skill       12343 non-null  object
 8   skill_demand_score  12343 non-null  int64
 9   job_openings        12343 non-null  int64
 10  job_survival_class  12343 non-null  int64
 11  salary_bucket       12343 non-null  object
 12  ai_risk_category    12343 non-null  object
dtypes: float64(2), int64(4), object(7)
memory usage: 1.2+ MB

To see and sum the null values if there are any in the dataset...in our case there's no null value

In [106]:
data.isnull().sum()

job_title             0
country               0
experience_level      0
education_level       0
year                  0
salary                0
ai_risk_score         0
primary_skill         0
skill_demand_score    0
job_openings          0
job_survival_class    0
salary_bucket         0
ai_risk_category      0
dtype: int64


<div class="alert alert-block alert-success">
    <h1>Step 3: Data Cleaning or Data Preperation</h1>
</div>

To see the null values in a specific column

In [107]:
data['country'].isnull().sum()

0

Mean --> Average value mostly used to fill numerical values

Mode --> Most repeated value used for string based value

Median --> Centermost value used to fill numerical values

We don't have any null value so we won't use these methods in this...

To remove a entire unnecessary column from the...

we're removing job_survival_class cause it's not really necessary

we're removing ai_risk_score because after changing the values into integer all the values becomes 0

We're removing salary bucket becausse it is a leakage

Skill demand score is also a leakage so we're removing this as well

We're removing ai_risk_category and job_openings because it's something we should predict and can't use it

We use inplace to save the changed data in our dataset

In [108]:
# # data['ai_risk_score'] = data.drop('ai_risk_score', axis=1)
data.drop('job_survival_class', axis=1, inplace=True)
data.drop('ai_risk_score', axis=1, inplace=True)
data.drop('salary_bucket', axis=1, inplace=True)
data.drop('ai_risk_category', axis=1, inplace=True)
data.drop('skill_demand_score', axis=1, inplace=True)
data.drop('job_openings', axis=1, inplace=True)

To find the mean and fill the missing column with that number...but we don't have any missing values

In [59]:
# data['Column name'] = data['Column name'].fillna(data['Column name'].mean())

Another method to fill values according to mean if we have more than one column to work with

In [19]:
# def fillnamean(column):
#   for i in column:
#     data[i]=data[i].fillna(data[i].mean())
# columns=["column name","other column name"]
# fillnamean(columns)

To fill the String values using mode

In [20]:
# data["column name"].mode()(0)

Another method to fill string values using mode

In [21]:
# def fillnamode(column):
#   for i in column:
#     data[i]=data[i].fillna(data[i].mode()(0))
# columns=["column name","Another column name","can add as many columns as we want"]
# fillnamode(columns)

Now, we'll change the datatype into integer

we'll use both methods for both float columns

In [22]:
#data["salary"]=data["salary"].astype("int64")

In [23]:
# def flotoint(column):
#   for i in column:
#     data[i]=data[i].astype("int64")
# columns=["ai_risk_score"]
# flotoint(columns)

To convert String(object) datatype into int64

In [24]:

#data["country"]=data["country"].replace({"USA":'1'})
#data['country'] = pd.factorize(data['country'])[0]
#data['job_title']=pd.factorize(data['job_title'])[0]
#data=data

In [25]:
#data["country"].unique()

In [26]:
#data['job_title'].unique()

In [109]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12343 entries, 0 to 12342
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_title         12343 non-null  object
 1   country           12343 non-null  object
 2   experience_level  12343 non-null  object
 3   education_level   12343 non-null  object
 4   year              12343 non-null  int64
 5   salary            12343 non-null  float64
 6   primary_skill     12343 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 675.1+ KB

2nd method to convert str into int

GPT

In [61]:
# job_title_LE = LabelEncoder()
# data['job_title'] = job_title_LE.fit_transform(data['job_title'])
# data.info()

To convert all object values into int

In [110]:
original_data = pd.read_csv('Future of Jobs AI Dataset.csv')

encoders = {}
columns = ['job_title', 'country', 'experience_level', 'education_level', 'primary_skill']

for col in columns:
    le = LabelEncoder()
    le.fit(original_data[col])         
    encoders[col] = le

joblib.dump(encoders, "encoders.pkl")
print("Encoders saved successfully.")

Encoders saved successfully.

In [111]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12343 entries, 0 to 12342
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_title         12343 non-null  object
 1   country           12343 non-null  object
 2   experience_level  12343 non-null  object
 3   education_level   12343 non-null  object
 4   year              12343 non-null  int64
 5   salary            12343 non-null  float64
 6   primary_skill     12343 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 675.1+ KB

In [112]:
data.to_csv('cleaned_data_csv',index=False, header=True)

<h1> Task 12 starts from here </h1>
<div class="alert alert-block alert-success">
    <h1>Step 4: Train-Test-Partitioning</h1>
</div>

In [135]:
data=pd.read_csv('cleaned_data_csv')
data

,job_title,country,experience_level,education_level,year,salary,primary_skill
0,Data Scientist,USA,Senior,Master,2022,61931.03,Python
1,Software Engineer,India,Senior,Bachelor,2032,21330.84,Java
2,Data Scientist,Canada,Mid,Bachelor,2015,24211.17,Python
3,Data Scientist,India,Entry,PhD,2034,11794.86,Python
4,Data Analyst,Canada,Entry,PhD,2035,17999.26,SQL
...,...,...,...,...,...,...,...
12338,Data Scientist,Germany,Entry,Master,2030,27079.49,Python
12339,Cybersecurity Analyst,USA,Mid,Bachelor,2028,42474.50,Security
12340,Software Engineer,India,Senior,Master,2028,19381.43,Java
12341,AI Researcher,Australia,Entry,PhD,2023,32647.87,Deep Learning
12342,DevOps Engineer,Australia,Entry,PhD,2023,23197.87,Docker

In [ ]:
data = pd.read_csv('cleaned_data_csv')
encoders = joblib.load("encoders.pkl")
categorical_cols = ['job_title', 'country', 'experience_level', 'education_level', 'primary_skill']
for col in categorical_cols:
    data[col] = encoders[col].transform(data[col])

In [137]:
data.tail()

,job_title,country,experience_level,education_level,year,salary,primary_skill
12338,5,2,0,1,2030,27079.49,5
12339,3,5,1,0,2028,42474.50,7
12340,9,3,2,1,2028,19381.43,4
12341,0,0,0,2,2023,32647.87,1
12342,6,0,0,2,2023,23197.87,2

In [138]:
data.columns

Index(['job_title', 'country', 'experience_level', 'education_level', 'year',
       'salary', 'primary_skill'],
      dtype='object')

We removed the columns we'll predict from the dataset and stored all 3 of them in a different variable

In [139]:
x=data.drop(['salary'],axis=1)
y_salary = data['salary']

x.head() gives us the dataset info without the 3 columns we removed

In [130]:
x.head()

,job_title,country,experience_level,education_level,year,primary_skill
0,Data Scientist,USA,Senior,Master,2022,Python
1,Software Engineer,India,Senior,Bachelor,2032,Java
2,Data Scientist,Canada,Mid,Bachelor,2015,Python
3,Data Scientist,India,Entry,PhD,2034,Python
4,Data Analyst,Canada,Entry,PhD,2035,SQL

y.head() gives us the infro of the 3 collumns we removed and stored in y

In [140]:
y_salary.head()

0    61931.03
1    21330.84
2    24211.17
3    11794.86
4    17999.26
Name: salary, dtype: float64

train_x means it's a feature for training
train_y means output for training
test_x meand feature for testing
test_y means output for testing
train_test_split is a function from scikit-learn that divides data into parts
test size means the data division that'll go for training and testing
0.2 test_size means 80% data goes to training and 20% data goes to testing
Shuffle False does'nt mixes data randomply

In [141]:
train_x, test_x, train_y_salary, test_y_salary=train_test_split(x,y_salary,test_size=0.2,shuffle=True,random_state=42)

In [142]:
# print(train_x.shape,train_y.shape)
# print(test_x.shape,test_y.shape)

In [143]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12343 entries, 0 to 12342
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_title         12343 non-null  int32
 1   country           12343 non-null  int32
 2   experience_level  12343 non-null  int32
 3   education_level   12343 non-null  int32
 4   year              12343 non-null  int64
 5   salary            12343 non-null  float64
 6   primary_skill     12343 non-null  int32
dtypes: float64(1), int32(5), int64(1)
memory usage: 434.1 KB

<div class= "alert alert-block alert-success">
    <h1>Step 5: Prediction phase/ Model application phase</h1>
</div>

We're using RandomForestRegressor because we need to predict...
n_estimators=200 means the model will make 200 trees... RandomForestRegressor works by making decision trees..
Random_state=42 is used when we need the same result everytime we run the code so to minimize errors... we can use any number but the same number

In [144]:
model_salary=RandomForestRegressor(n_estimators=200,random_state=42)
model_salary.fit(train_x,train_y_salary)

RandomForestRegressor(n_estimators=200, random_state=42)

In [145]:
pred_salary=model_salary.predict(test_x)

We're using pickle to save the objects...wb means write in binary

In [146]:
with open('random_forest_model.pkl', 'wb') as f:
    pickle.dump(model_salary, f)
print("Model saved as random_forest_model.pkl")

Model saved as random_forest_model.pkl

We're loading the model

In [147]:
with open('random_forest_model.pkl', 'rb') as f:
    loaded_model = pickle.load(f)

<div class = "alert alert-block alert-success">
    <h1>Step 6: Model Accuracy</h1>
</div>

In [154]:
pred_salary = model_salary.predict(test_x)

print(f"Salary R square : {r2_score(test_y_salary, pred_salary)*100:.3f}")

Salary R square : 98.029

<div class = "alert alert-block alert-success">
    <h1>Step 7: Application phase</h1>
</div>

Loading the trained model

Loading the saved encoders

A function that'll take user's input and return the particular number saved in model

Taking user's inputs

Each categorical column is replaced with numerical value

Defined the order of features

Created a 2D numpy array

In [150]:
model = pickle.load(open('random_forest_model.pkl', 'rb'))
encoders = joblib.load("encoders.pkl")

def encode_cols(le, value):
    value_lower = value.lower()
    for original in le.classes_:
        if original.lower() == value_lower:
            return le.transform([original])[0]
    raise ValueError(f"Invalid value '{value}'. Allowed: {list(le.classes_)}")

print("Enter user input:")
user_input = {
    "job_title": input("Job_Title: "),
    "country": input("Country: "),
    "experience_level": input("Experience level: "),
    "education_level": input("Education level: "),
    "year": int(input("Year: ")),
    "primary_skill": input("Primary skill: ")
}

for col in ['job_title', 'country', 'experience_level', 'education_level', 'primary_skill']:
    user_input[col] = encode_cols(encoders[col], user_input[col])

features = ['job_title', 'country', 'experience_level', 'education_level', 'year', 'primary_skill']
X = np.array([[user_input[col] for col in features]])

pred_salary = model.predict(X)[0]
print(f"Predicted Salary: {pred_salary:.2f}")

Enter user input:
Predicted Salary: 43992.74

c:\Users\jsarm\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(